# SPDX-License-Identifier: Apache-2.0
"""Print a deterministic checksum manifest for bundled Gross/BB144 assets."""

from __future__ import annotations

import hashlib
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = REPO_ROOT / "grosscode" / "assets" / "gross144"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def iter_asset_rows() -> list[tuple[str, int, str]]:
    """Return sorted `(path, size_bytes, sha256)` rows for bundled assets."""

    rows: list[tuple[str, int, str]] = []
    for path in sorted(ASSET_ROOT.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        rows.append((rel, path.stat().st_size, _sha256(path)))
    return rows


def main() -> int:
    print("# Asset Manifest")
    print()
    print("Generated by `python -m tools.asset_manifest`.")
    print()
    print("| Path | Size bytes | SHA256 |")
    print("| --- | ---: | --- |")
    for rel, size, digest in iter_asset_rows():
        print(f"| `{rel}` | {size} | `{digest}` |")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
