# SPDX-License-Identifier: Apache-2.0
"""Print a deterministic checksum manifest for retained data files."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = REPO_ROOT / "grosscode" / "assets" / "gross144"
SKIPPED_FILENAMES = {".DS_Store", "MANIFEST.md"}


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _display_path(path: Path) -> str:
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def iter_asset_rows(root: Path = ASSET_ROOT) -> list[tuple[str, int, str]]:
    """Return sorted `(path, size_bytes, sha256)` rows under `root`."""

    rows: list[tuple[str, int, str]] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.name in SKIPPED_FILENAMES:
            continue
        rel = _display_path(path)
        rows.append((rel, path.stat().st_size, _sha256(path)))
    return rows


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default=str(ASSET_ROOT),
        help="Directory to checksum. Defaults to the bundled Gross/BB144 asset root.",
    )
    parser.add_argument(
        "--title",
        default="Asset Manifest",
        help="Markdown title to print.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    root = Path(args.root)
    if not root.is_absolute():
        root = REPO_ROOT / root
    if not root.exists() or not root.is_dir():
        raise SystemExit(f"manifest root is not a directory: {root}")

    print(f"# {args.title}")
    print()
    if root == ASSET_ROOT:
        print("Generated by `python -m tools.asset_manifest`.")
    else:
        root_label = _display_path(root)
        print(
            "Generated by "
            f"`python -m tools.asset_manifest --root {root_label} --title \"{args.title}\"`."
        )
    print()
    print("| Path | Size bytes | SHA256 |")
    print("| --- | ---: | --- |")
    for rel, size, digest in iter_asset_rows(root):
        print(f"| `{rel}` | {size} | `{digest}` |")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
